# Generated by Django 5.2.4 on 2026-02-19 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('gratuit', 'Gratuit'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='gratuit', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('telechargements_inclus', models.PositiveIntegerField(default=3)),
                ('telechargements_utilises', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epreuve_id', models.PositiveIntegerField()),
                ('epreuve_title', models.CharField(max_length=200)),
                ('matiere', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=20)),
                ('annee', models.PositiveSmallIntegerField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'verbose_name_plural': 'Téléchargements',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('downloads_this_month', models.PositiveIntegerField(default=0)),
                ('last_download_date', models.DateTimeField(blank=True, null=True)),
                ('favorite_matiere', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques utilisateur',
                'verbose_name_plural': 'Statistiques utilisateurs',
            },
        ),
    ]
