# Generated by Django 5.2.4 on 2026-02-21 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('cycle', models.CharField(choices=[('primaire', 'Enseignement Primaire'), ('college', 'Premier Cycle (Collège)'), ('lycee', 'Second Cycle (Lycée)')], max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('has_serie', models.BooleanField(default=False, help_text='A des séries (A, C, D...)')),
                ('has_examen_final', models.BooleanField(default=False, help_text='A un examen final (CEP, BEPC, Bac)')),
                ('nom_examen', models.CharField(blank=True, help_text='Ex: BEPC, Baccalauréat', max_length=50)),
            ],
            options={
                'verbose_name': 'Niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('s1', '1er Semestre'), ('s2', '2ème Semestre'), ('t1', '1er Trimestre'), ('t2', '2ème Trimestre'), ('t3', '3ème Trimestre'), ('exam', 'Examen Final')], max_length=5, unique=True)),
                ('nom', models.CharField(max_length=30)),
                ('numero', models.PositiveSmallIntegerField(help_text='1, 2 ou 3')),
                ('mois_debut', models.CharField(blank=True, max_length=20)),
                ('mois_fin', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Période',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_systeme', models.CharField(choices=[('semestriel', 'Système Semestriel (Collège/Lycée)'), ('trimestriel', 'Système Trimestriel (Primaire)')], max_length=15)),
                ('nombre_periodes', models.PositiveSmallIntegerField(help_text='2 pour semestriel, 3 pour trimestriel')),
            ],
            options={
                'verbose_name': 'Système Scolaire',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('couleur', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, default='📚', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('niveaux', models.ManyToManyField(blank=True, related_name='matieres', to='epreuves.niveau')),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('numero_classe', models.PositiveSmallIntegerField(help_text='1 pour CP1/6ème, 2 pour CP2/5ème... 4 pour Terminale')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='epreuves.niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['niveau__ordre', 'numero_classe'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('nom_complet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#6366f1', max_length=7)),
                ('matieres_principales', models.ManyToManyField(blank=True, related_name='series_principales', to='epreuves.matiere')),
            ],
            options={
                'verbose_name': 'Série',
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('annee_scolaire', models.CharField(default='2023-2024', help_text='Format: 2023-2024', max_length=9)),
                ('type_epreuve', models.CharField(choices=[('composition_1', '1ère Composition'), ('composition_2', '2ème Composition'), ('evaluation_1', '1ère Évaluation'), ('evaluation_2', '2ème Évaluation'), ('evaluation_3', '3ème Évaluation'), ('ceped', 'CEPED'), ('cepd', 'CEPD'), ('bepc', 'BEPC'), ('bac_1', 'Baccalauréat 1er Tour'), ('bac_2', 'Baccalauréat 2ème Tour'), ('bac_blanc', 'Bac Blanc'), ('concours', "Concours d'entrée"), ('examen_entree', "Examen d'entrée")], max_length=20)),
                ('session', models.CharField(blank=True, choices=[('normale', 'Session Normale'), ('remplacement', 'Session de Remplacement'), ('rattrapage', 'Rattrapage')], default='normale', max_length=20)),
                ('duree', models.CharField(blank=True, help_text='Ex: 2h, 4h, 5h30', max_length=20)),
                ('coefficient', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bareme', models.PositiveSmallIntegerField(default=20, help_text='Barème sur 20 ou 400')),
                ('fichier_sujet', models.FileField(upload_to='epreuves/sujets/%Y/%m/')),
                ('fichier_corrige', models.FileField(blank=True, null=True, upload_to='epreuves/corriges/%Y/%m/', verbose_name='Corrigé type')),
                ('fichier_rapport', models.FileField(blank=True, null=True, upload_to='epreuves/rapports/%Y/%m/', verbose_name="Rapport de l'épreuve (pour examens officiels)")),
                ('enonce', models.TextField(blank=True, help_text="Texte de l'énoncé (optionnel)")),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions spéciales')),
                ('nombre_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='En Ko', null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('date_epreuve', models.DateField(blank=True, help_text="Date réelle de l'épreuve", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.niveau')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.periode')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='epreuves.serie')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['-annee_scolaire', 'periode__code', 'matiere__nom'],
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='epreuves.systemescolaire'),
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('a_telecharge_sujet', models.BooleanField(default=True)),
                ('a_telecharge_corrige', models.BooleanField(default=False)),
                ('utilise_credit_gratuit', models.BooleanField(default=False)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='epreuves.epreuve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements_epreuves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_telechargement'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='epreuves.epreuve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_epreuves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'epreuve')},
            },
        ),
        migrations.AddIndex(
            model_name='epreuve',
            index=models.Index(fields=['annee_scolaire', 'classe', 'periode'], name='epreuves_ep_annee_s_59b0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='epreuve',
            index=models.Index(fields=['type_epreuve', 'matiere'], name='epreuves_ep_type_ep_2128cb_idx'),
        ),
        migrations.AddIndex(
            model_name='epreuve',
            index=models.Index(fields=['slug'], name='epreuves_ep_slug_4f67a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telechargement',
            unique_together={('user', 'epreuve')},
        ),
    ]
