# Generated by Django 5.2.4 on 2026-02-21 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#6366f1', max_length=7)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('extrait', models.TextField(blank=True, help_text='Premières pages pour preview')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('annee_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='Français', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='livres/pdf/%Y/')),
                ('fichier_epub', models.FileField(blank=True, null=True, upload_to='livres/epub/%Y/')),
                ('format_disponible', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('both', 'PDF + EPUB')], default='pdf', max_length=10)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='livres/covers/%Y/')),
                ('prix', models.PositiveIntegerField(default=0, help_text='Prix en FCFA, 0 = gratuit avec abonnement')),
                ('is_premium', models.BooleanField(default=True, help_text='Nécessite un abonnement actif')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre_lectures', models.PositiveIntegerField(default=0)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='livres.categorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_actuelle', models.PositiveIntegerField(default=1)),
                ('pourcentage', models.PositiveSmallIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('termine', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_users', to='livres.livre')),
            ],
            options={
                'verbose_name': 'Progression de lecture',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_approuve', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_livres', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='livres.livre')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AchatLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.PositiveIntegerField()),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_livres', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='livres.livre')),
            ],
            options={
                'verbose_name': 'Achat de livre',
            },
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['categorie', 'is_premium'], name='livres_livr_categor_6f194a_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['slug'], name='livres_livr_slug_c35cbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('user', 'livre')},
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('user', 'livre')},
        ),
        migrations.AlterUniqueTogether(
            name='achatlivre',
            unique_together={('user', 'livre')},
        ),
    ]
